chore: add phpmd to pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -126,6 +126,38 @@ else
   printf "\nphpstan is required. Install it with:\n\n  ddev composer req --dev phpstan/phpstan\n\n"
 fi
 
+HAS_PHPMD=false
+PHPMD="./vendor/bin/phpmd"
+if [ -x $PHPMD ]; then
+    HAS_PHPMD=true
+fi
+
+run_phpmd() {
+  ddev exec "$PHPMD" "$1" text ruleset.xml
+}
+
+if $HAS_PHPMD; then
+  STAGED_PHP_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.php$' | tr '\n' ',')
+
+  if [ -z "$STAGED_PHP_FILES" ]; then
+    printf "${YELLOW}PHP Mess Detector${NC} — no PHP files staged, skipping.\n"
+  else
+    STAGED_PHP_FILES="${STAGED_PHP_FILES%,}"
+    printf "${YELLOW}PHP Mess Detector${NC}\n"
+
+    run_phpmd "$STAGED_PHP_FILES"
+    if [ $? -eq 0 ]; then
+      printf "${GREEN}PASSED${NC}\n"
+    else
+      printf "${RED}FAILED${NC}\n"
+      PASS=false
+    fi
+  fi
+else
+  printf "\nphpmd is required. Install it with:\n\n  composer require --dev phpmd/phpmd\n\n"
+fi
+
+
 # you shouldn't be able to commit if composer.lock and composer.json are out of sync
 printf "${YELLOW}Composer Lockfile${NC}\n"
 RUN composer validate --no-check-all --no-check-publish
